# Projeniz için küresel bir platform tanımlamak üzere bir sonraki satırı yorumdan çıkarın
 platform :ios, '14.5'

target 'Runner' do
  # Dinamik frameworkler kullanmak istemiyorsanız bir sonraki satırı yorumlayın
  use_frameworks!

  # Runner için Podlar
  pod 'Firebase/Firestore'
  pod 'google_maps_flutter_ios'

  # permission_handler yapılandırmasının başlangıcı
  target.build_configurations.each do |config|
    config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
      '$(inherited)',
      'PERMISSION_CAMERA=1',
      'PERMISSION_MICROPHONE=1',
    ]
  end
  # permission_handler yapılandırmasının sonu

  target 'RunnerTests' do
    inherit! :search_paths
    # Testler için Podlar
  end

end
